/*
* 首页JS V1.0
* JS代码经过压缩提升加载速度
*/

//49介绍图切换
function Slideid(){var a=location.search;if(a.length>1){a=a.substring(1);var b=a.split("&");var c="";for(var i=0;i<b.length;i++){var d=b[i].split("=");if(d.length>1){if(d[0].toLowerCase()=="oid"){c=d[1]-1}else{c=-1}}};if(c<0){c=-1}}else{c=-1};return c};var focusimgplayer=(function(){var f={container:".slide-con",delay:5000,menu:".slide-nav",imgsrc:"originalsrc",index:0,current_focus:null,current_focus_img_list:null,timer:null};var g=function(a){var b=$(f.container);if(b.length==0){return};f.current_focus=b.eq(0);$("li",b).hide();f.current_focus_img_list=$("a > img",f.current_focus);var c=$("li",f.current_focus).size();if(!a||a>c){a=0};f.index=a;b.children().children().eq(f.index).show();j(f.index);h();$(f.menu+" li").mouseover(function(){f.index=parseInt($(this).text())-1;j(f.index);if(f.index>=c)return;$("li",f.container).filter(":visible").fadeOut(150,function(){$(this).parent().children().eq(f.index).fadeIn(150)});$(this).css({"background-position":" 0px 0px"}).siblings().css({"background-position":" -21px 0px"})}).eq(f.index).css({"background-position":" 0px 0px"});f.timer=setInterval(k,f.delay);f.current_focus.hover(function(){f.timer&&(clearInterval(f.timer))},function(){f.timer=setInterval(k,f.delay)})};var h=function(){var a="<ul>";var b=$("a",f.current_focus).size();for(i=1,l=b;i<=l;i++){a=a+"<li>"+i+"</li>"};a=a+"</ul>";$(f.menu).html(a)};var j=function(a){if(f.current_focus_img_list.length==0){return};var b=$("a",f.current_focus).eq(a).children().length;for(p=0;p<=b;p++){var c=$("a",f.current_focus).eq(a).children().eq(p);var d=c.attr(f.imgsrc);var e=c.attr('src');e||!d||(c.attr('src',d),c.removeAttr(f.imgsrc))}};var k=function(){f.index=f.index>=($("a",f.current_focus).size()-1)?0:++f.index;$(f.menu+" li").eq(f.index).trigger('mouseover')};return{init:function(a){$.extend(f,a)},imgplayer:g}})();$(function(){var p_num=Slideid();if(p_num==-1){p_num=0};focusimgplayer.imgplayer(p_num);var round1=Math.round(Math.random()*9+1);if(round1<=5){$("#box-jd-06").attr("columnid","118")}else{$("#box-jd-06").attr("columnid","119")}var SmartAdList=$("#box-jd-06")});

//左侧游戏子导航
$(function(){$("#subnav_list li").live('mouseenter',function(){var hoverobject=$(this).children(".subnav_hover"),hoverimg=hoverobject.children("img"),hoverloadsrc=hoverimg.attr("loadsrc"),hoversrc=hoverimg.attr("src");hoverobject.show()}).live('mouseleave',function(){$(this).children(".subnav_hover").hide()})});

//最新活动滚动切换
var ul=$('.ks-switchable-content ul');while(true){if(!ul.find('li:eq(10)').length)break;var new_ul=$('<ul></ul>');for(var i=0;i<10;i++){var last_li=ul.find('li:eq(10)');if(!last_li.length)break;new_ul.append(last_li)}$('.ks-switchable-content ul:last').after(new_ul)}function _switch(dir,callback){var div=$('div.ks-switchable-content');var px=parseInt(div.css('top').replace(/[^0-9-]/g,''));var count=div.find('ul').length;var width=$('div.tab-bd').height();var max_px=width*count-width;var dis;if(dir=='left'){dis=px==0?0:px+width}else{dis=px<=-max_px?-max_px:px-width}var current=Math.abs(Math.min(dis,0)/width)+1;current=Math.min(count,current);div.animate({'top':dis},200,callback);$('#txt-page').html(current+'/'+count)}$(function(){$('.ks-switchable-content ul').each(function(k,v){if(v===ul&&k>0){(function(offset){var func=arguments.callee;_switch('right',function(){if(!--offset)return;func(offset)})})(k);return false}})});

//最热门网页游戏
$(function(){$(".game-show-box").each(function(){$(this).hover(function(){var gameMin=$(this).attr("data-gamemin");var inGameArr=$(this).find("dl dd a");if(!inGameArr.attr("href")||inGameArr.attr("href")=='javascript:;'){getServerInfo(gameMin,inGameArr)}$(this).parent("li").addClass("curr")},function(){$(this).parent("li").removeClass("curr")})})});

//幻灯片插件
;(function($){$.fn.extend({XYcarousel:function(params){var p=$.extend({prev:"#buttonPrev",next:"#buttonNext",frame:this.children(),child:"",direction:"horizontal",width:"",height:"",auto:true,autoTime:3000,animateTime:"normal"},params);var _btnNext=$(p.next),_btnPrev=$(p.prev),_imgFrame=$(p.frame),_child=p.child==""?_imgFrame.children().get(0).tagName:p.child,_width=p.width==""?_imgFrame.children(_child).width():p.width,_height=p.height==""?_imgFrame.children(_child).height():p.height,_distance=p.direction!="vertical"?_width:_height,_direction=p.direction!="vertical"?"marginLeft":"marginTop",_css=p.direction!="vertical"?"margin-left":"margin-top",_animate={},_direction,_auto=p.auto,_click=true,_timeout,_itv;_btnPrev.click(function(){if(_click==true){_click=false;if(_auto){autoStop();};_animate[_direction]=0;_imgFrame.find(_child+":last").prependTo(_imgFrame);_imgFrame.css(_css,-_distance);_imgFrame.stop().animate(_animate,p.animateTime,function(){_click=true;if(_auto){autoPlay();};});};});_btnNext.click(function(){if(_click==true){_click=false;if(_auto){autoStop();};_animate[_direction]=-_distance;_imgFrame.stop().animate(_animate,p.animateTime,function(){_imgFrame.find(_child+":first").appendTo(_imgFrame);_imgFrame.css(_css,0);_click=true;if(_auto){autoPlay();};});};});var autoPlay=function(){_itv=window.setInterval(function(){_btnNext.click();},p.autoTime);};var autoStop=function(){window.clearInterval(_itv);};if(_auto){autoPlay();_imgFrame.hover(function(){if(_imgFrame.is(":animated")){_timeout=setTimeout(function(){_click=false;},p.animateTime);}else{_click=false;};},function(){clearTimeout(_timeout);_click=true;});};}});})(jQuery);

//首屏焦点banner滚动效果
$(function(){if($("#game-hot-show ul").length>1){$("#game-hot-show").XYcarousel({prev:"#banner_prev",next:"#banner_next",autoTime:4000,animateTime:500});};});